name: "Deploy Website to S3"
description: "Builds and deploys a React website to S3"

inputs:
  organization:
    description: "GitHub organization name"
    required: true
  project:
    description: "Project name"
    required: true
  gh-token:
    description: "GitHub token for repository access"
    required: true
  ref:
    description: "Git reference to checkout for react, project-react, and react-shared"
    required: false
    default: ${{ github.ref }}
  aws-access-key-id:
    description: "AWS Access Key ID"
    required: true
  aws-secret-access-key:
    description: "AWS Secret Access Key"
    required: true
  s3-bucket:
    description: "S3 bucket name"
    required: true
    default: "cdn.bighelp.ai"

runs:
  using: "composite"
  steps:
    - name: Checkout app repository
      uses: actions/checkout@v4

    - name: Checkout react-shared repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.organization }}/react-shared
        ref: ${{ inputs.ref }}
        token: ${{ inputs.gh-token }}
        path: react-shared

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "20"

    - name: Install dependencies
      shell: bash
      run: npm install

    - name: Build app
      shell: bash
      run: REACT_SHARED=$GITHUB_WORKSPACE/react-shared node_modules/.bin/vite build

    - name: Upload to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read
      env:
        SOURCE_DIR: dist/
        DEST_DIR: ${{ inputs.project }}
        AWS_S3_BUCKET: ${{ inputs.s3-bucket }}
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
